"""empty message

Revision ID: 7066ee3e02f5
Revises: fff6fe7a6581
Create Date: 2022-08-07 08:45:32.122164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7066ee3e02f5'
down_revision = 'fff6fe7a6581'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('course', 'time',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=250),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('course', 'time',
               existing_type=sa.String(length=250),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
